name: Deploy Azure Storage Account

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  RESOURCE_GROUP: RG-Sandbox-EU-Cloud-scambler
  LOCATION: westeurope
  STORAGE_ACCOUNT_NAME: storagescambler001

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Deploy to TEST
        run: echo "Deploying to TEST"
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Bicep template
        uses: azure/arm-deploy@v2
        with:
          resourceGroupName: ${{ env.RESOURCE_GROUP }}
          template: ./main.bicep
          parameters: >
            storageAccountName=${{ env.STORAGE_ACCOUNT_NAME }}
            location=${{ env.LOCATION }}
